### ISSUE TITLE
qtip2 fails to load all the dependencies

### ISSUE THREAD

**Issue by vivekkandhvar** [webjars/qtip2#1]
Throws the following error.

> Could not find any matches for org.webjars.bower:imagesloaded:[3.0.0,) as no versions of org.webjars.bower:imagesloaded are available.

Required by:
      com.xxx.abc:pqr-st:1.0-SNAPSHOT > org.webjars.bower:qtip2:2.2.1

**Comment by jamesward** [comment]
Unfortunately that dependency can't be deployed via [webjars.org/bower](http://webjars.org/bower) because the license can't be determined.  I've submitted a PR to have them add a license: https://github.com/desandro/imagesloaded/pull/200

**Comment by vivekkandhvar** [comment]
That helps. Thanks a lot James.

**Comment by jamesward** [comment]
In the meantime you can tell your build to exclude the transitive dependency on `org.webjars.bower:imagesloaded:[3.0.0,)` and instead pull it in via the classic WebJar:

```
"org.webjars" % "imagesloaded" % "3.1.8"
```

**Comment by desandro** [comment]
I prefer not to include LICENSE files. Any way we can side-stop this?

**Comment by jamesward** [comment]
@desandro You can also specify the license in the `bower.json` but that won't be useful for us until your next release.

**Comment by desandro** [comment]
Great! I'll do that instead.
