### ISSUE TITLE
Missing source maps

### ISSUE THREAD

**Issue by maurercw** [webjars/qtip2#5]
Would it also be possible to include the source maps?  There should be a file like jquery.qtip.min.map in the main directory as well as in the basic directory.

**Comment by jamesward** [comment]
Do you need them for a particular version?

**Comment by maurercw** [comment]
The latest, which I believe was 3.0.3 is what I needed.  Thanks!

Chris

**Comment by jamesward** [comment]
This will be released as `3.0.3-1`
